### ISSUE TITLE
Porting to Python

### ISSUE THREAD

**Issue by jhagege** [flo-l/openscad-text#1]
Hi, I'm interested to port your library to Python, but I don't really understand the algorithms on a high level.

How is the font rendering done? Do you extract it to some vector path before exporting to OpenSCAD?
What kind of helper libraries help with that?

Thanks a lot

**Comment by flo-l** [comment]
Hi! I'm happy to help you with my code! But I have to apologise in advance, the whole thing is rather hacky and by no means an elegant solution :laughing: 

The code uses ImageMagick to render some text with some font into a temporary image file. (see [here](https://github.com/flo-l/openscad-text/blob/master/lib/openscad-text/text.rb#L21-L32))

It then reads this file and tries to find "pixel chains". By pixel chains I mean the pixels at the borders of the letters in order. [code](https://github.com/flo-l/openscad-text/blob/master/lib/openscad-text/text.rb#L119-L136)

[This code](https://github.com/flo-l/openscad-text/blob/master/lib/openscad-text/text.rb#L69-L115) is responsible for finding the next pixel in a pixel chain. It searches by visiting all 8 neighbours of the current pixel and finally finds the next chain link.

Initially I planned to extract vector paths etc. etc., but I have no time to work on this little toy project currently. The thing my code does is barely better than just placing a [1,1,1]-cube everywhere a pixel is black. I would suggest either doing it right (probably with some python image processing lib that can extract vec paths) or doing it dead simple with the cubes. The thing I have produced took me some time but the results are hardly better than they were with cubes, so I'm not at all satsfied with it.

Hope that helps a bit!

**Comment by jhagege** [comment]
Thanks a lot for your help.
Very hackish and smart way to do it :-)
